Repository AY2223S2-CS2103T-W14-3/tp, pull requests merged in 2023-03, with the labels that each got.

#15 Update pull_request_template.md
  docs/pull_request_template.md
Labels: type.Documentation

#18 create clevon-w.md
  docs/clevon-w.md
Labels: type.Documentation

#17 Create homuntan02.md
  docs/homuntan02.md
Labels: type.Documentation

#19 Create panpannnnn.md
  docs/panpannnnn.md
Labels: type.Documentation

#25 24-update-yyj-02-about-us
  docs/AboutUs.md
  docs/images/yyj-02.png
  docs/team/yyj-02.md
Labels: type.Documentation

#16 12-add-listing-package
  src/main/java/seedu/address/model/listing/JobDescription.java
  src/main/java/seedu/address/model/listing/JobTitle.java
  src/main/java/seedu/address/model/listing/Listing.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/listing/JobDescriptionTest.java
  src/test/java/seedu/address/model/listing/JobTitleTest.java
  src/test/java/seedu/address/model/listing/ListingTest.java
  src/test/java/seedu/address/testutil/ListingBuilder.java
  src/test/java/seedu/address/testutil/TypicalListings.java
Labels: type.Listing, priority.CoreFeature, medium

#33 Update about us for myself
  docs/AboutUs.md
  docs/images/clevon-w.png
  docs/team/clevon-w.md
Labels: type.Documentation

#35 34-Update-About-Us-nt-nic
  docs/AboutUs.md
  docs/images/nt-nic.png
  docs/team/nt-nic.md
Labels: type.Documentation

#44 37-delete-ppp
  docs/clevon-w.md
  docs/homuntan02.md
  docs/nt-nic.md
  docs/panpannnnn.md
  docs/yyj-02.md
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: type.Documentation

#46 36-Update-AboutUs-for-panpannnnn
  docs/AboutUs.md
  docs/images/branda.jpg
  docs/team/panpannnnn.md
Labels: type.Documentation

#22 13-add-applicant-class
  src/main/java/seedu/address/model/applicant/Applicant.java
  src/main/java/seedu/address/model/applicant/Name.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/applicant/ApplicantTest.java
  src/test/java/seedu/address/model/applicant/NameTest.java
  src/test/java/seedu/address/testutil/ApplicantBuilder.java
  src/test/java/seedu/address/testutil/TypicalApplicants.java
Labels: type.Applicant, priority.CoreFeature, medium

#27 26-update-readme
  README.md
  docs/_sass/minima/_base.scss
Labels: type.Documentation

#29 28-add-user-guide
  docs/UserGuide.md
Labels: type.Documentation

#48 47-add-applicant-to-listing
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/model/listing/Listing.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/listing/ListingTest.java
  src/test/java/seedu/address/testutil/ListingBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalListings.java
Labels: type.Listing, type.Applicant, priority.CoreFeature, easy

#56 55-Update Developer Guide
  docs/DeveloperGuide.md
Labels: type.Documentation

#52 6 - Post a job listing feature for Recruiters
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ListingBookParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/resources/view/DarkTheme.css
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/model/listing/ListingTest.java
  src/test/java/seedu/address/testutil/TypicalListings.java
Labels: type.Listing, priority.CoreFeature

#59 8-Implement-Delete-Command
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/ListingBookParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
Labels: priority.CoreFeature

#67 Update User Guide
  docs/UserGuide.md
  docs/images/Screenshot_2023-03-15_at_1.02.55_AM.png
  docs/images/helpMessage.png
Labels: type.Documentation

#74 Update GoodMatch Icon
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/GoodMatch_logo.png
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/MainWindow2.fxml
  src/test/java/seedu/address/commons/util/AppUtilTest.java
Labels: priority.Enhancement

#73 Update User Guide image
  docs/UserGuide.md
Labels: type.Documentation

#85 68-edit-css
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/view/ExtensionsDark.css
  src/main/resources/view/ExtensionsLight.css
  src/main/resources/view/LightTheme.css
  src/main/resources/view/MainWindow2.fxml
Labels: priority.Enhancement

#91 90-Change extension of image
  docs/AboutUs.md
  docs/images/branda.png
Labels: type.Documentation

#96 95-Update-DG-with-Undo
  docs/DeveloperGuide.md
Labels: type.Documentation

#102 99-Update DG with use case for edit applicant
  docs/DeveloperGuide.md
Labels: type.Documentation

#104 101-adding-things-to-the-dg
  docs/DeveloperGuide.md
Labels: type.Documentation

#108 106-update-the-ug
  docs/UserGuide.md
  docs/images/Ui.png
  src/main/resources/view/MainWindow.fxml
Labels: type.Documentation

#107 105 dev guide update
  docs/DeveloperGuide.md
  docs/SettingUp.md
  docs/_config.yml
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/index.md
Labels: type.Documentation, medium

#110 109-fix-edit-applicant
  src/main/java/seedu/address/logic/commands/AddApplicantCommand.java
  src/main/java/seedu/address/logic/commands/EditApplicantCommand.java
Labels: priority.Bug

#114 112 ug review
  docs/UserGuide.md
  docs/images/Screenshot_2023-03-15_at_1.02.55_AM.png
  docs/images/helpMessage.png
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/model/listing/Listing.java
  src/test/java/seedu/address/model/listing/ListingTest.java
Labels: type.Documentation, easy

#111 89-add-autocompletion
  bin/main/seedu/address/logic/autocompletion/Autocompletion$1.class
  bin/main/seedu/address/logic/autocompletion/Autocompletion.class
  bin/main/seedu/address/ui/CommandBox.class
  bin/main/seedu/address/ui/MainWindow.class
  bin/main/seedu/address/ui/UiManager.class
  bin/main/view/CommandBox.fxml
  bin/main/view/ExtensionsDark.css
  bin/main/view/ExtensionsLight.css
  bin/main/view/HelpWindow.fxml
  bin/main/view/HelpWindowDark.css
  bin/main/view/HelpWindowLight.css
  bin/main/view/LightTheme.css
  bin/main/view/ListingListCard.fxml
  bin/main/view/ListingListPanel.fxml
  bin/main/view/MainWindow2.fxml
  src/main/java/seedu/address/logic/autocompletion/Autocompletion.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/resources/view/CommandBox.fxml
  src/test/java/seedu/address/logic/autocompletion/AutocompletionTest.java
Labels: priority.Enhancement

#94 69-Add-undo-command
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/parser/ListingBookParser.java
  src/main/java/seedu/address/model/ListingBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: type.Listing, type.Applicant, priority.Enhancement, medium

#120 116-add-platform-released
  src/main/java/seedu/address/logic/commands/AddApplicantCommand.java
  src/main/java/seedu/address/logic/commands/AddPlatformCommand.java
  src/main/java/seedu/address/logic/commands/DeleteApplicantCommand.java
  src/main/java/seedu/address/logic/commands/DeletePlatformCommand.java
  src/main/java/seedu/address/logic/commands/EditApplicantCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddPlatformCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DeletePlatformCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ListingBookParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/listing/Listing.java
  src/main/java/seedu/address/model/platform/Platform.java
  src/main/java/seedu/address/model/platform/PlatformName.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedListing.java
  src/main/java/seedu/address/storage/JsonAdaptedPlatform.java
  src/main/java/seedu/address/ui/ListingCard.java
  src/main/resources/view/LightTheme.css
  src/main/resources/view/ListingListCard.fxml
  src/test/java/seedu/address/logic/commands/AddPlatformCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddPlatformCommandParserTest.java
  src/test/java/seedu/address/model/listing/ListingTest.java
  src/test/java/seedu/address/model/platform/PlatformNameTest.java
  src/test/java/seedu/address/model/platform/PlatformTest.java
  src/test/java/seedu/address/testutil/EditListingDescriptorBuilder.java
  src/test/java/seedu/address/testutil/ListingBuilder.java
  src/test/java/seedu/address/testutil/PlatformBuilder.java
  src/test/java/seedu/address/testutil/TypicalListings.java
  src/test/java/seedu/address/testutil/TypicalPlatforms.java
Labels: type.Listing, priority.Enhancement
