Repository AY2223S2-CS2103T-W14-3/tp, pull requests merged in 2023-04, with the labels that each got.

#181 124-133-141-Update UG url
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: PED-low, PED-med

#191 Update UG with add_app, edit_app, del_app.
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/DeleteApplicantCommand.java
  src/main/java/seedu/address/logic/commands/EditApplicantCommand.java
  src/test/java/seedu/address/logic/commands/DeleteApplicantCommandTest.java
Labels: type.Documentation

#193 190-Update UG
  docs/UserGuide.md
  docs/images/Ui.png
Labels: type.Documentation

#194 190 resolve ug bugs
  docs/UserGuide.md
Labels: type.Documentation

#192 135-157-180 fix undo
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/UndoCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: priority.Bug, medium

#195 134-145-162-170-Update UG, edit error message
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/EditCommand.java
Labels: type.Documentation

#200 197-update-dg-undo-functio
  docs/DeveloperGuide.md
  docs/images/CommitActivityDiagram.png
  docs/images/UndoSequenceDiagram.png
  docs/images/UndoState0.png
  docs/images/UndoState1.png
  docs/images/UndoState2.png
  docs/images/UndoState3.png
  docs/images/UndoState4.png
Labels: type.Documentation

#201 add-some-diagrams-to-dg
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/AutocompleteActivityDiagram.puml
  docs/diagrams/AutocompleteSequenceDiagram.puml
  docs/diagrams/UndoActivityDiagram.puml
  docs/images/AutocompleteActivityDiagram.png
  docs/images/AutocompleteSequenceDiagram.png
  docs/images/UndoActivityDiagram.png
Labels: type.Documentation

#185 121-add-more-tests-for-platform-commands
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeletePlatformCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddPlatformCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeletePlatformCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/testutil/EditListingDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PlatformBuilder.java
Labels: priority.Enhancement, type.Platform

#205 203-Update DG to include diagrams for sort command
  docs/DeveloperGuide.md
  docs/diagrams/SortActivityDiagram.puml
  docs/diagrams/SortSequenceDiagram.puml
  docs/diagrams/UndoRedoState0.puml
  docs/diagrams/UndoRedoState1.puml
  docs/diagrams/UndoRedoState2.puml
  docs/diagrams/UndoRedoState3.puml
  docs/diagrams/UndoRedoState4.puml
  docs/diagrams/UndoRedoState5.puml
  docs/images/SortActivityDiagram.png
  docs/images/SortSequenceDiagram.png
  docs/images/johndoe.png
Labels: type.Documentation

#208 207-fix-case-insensitivity
  src/main/java/seedu/address/logic/parser/ListingBookParser.java
Labels: priority.Bug

#209 202 add dg diagrams for find
  docs/DeveloperGuide.md
  docs/diagrams/FindActivityDiagram.puml
  docs/diagrams/FindSequenceDiagram.puml
  docs/images/FindActivityDiagram.png
  docs/images/FindSequenceDiagram.png
Labels: type.Documentation

#212 211-Update PPP and AboutUs
  docs/AboutUs.md
  docs/team/clevon-w.md
  docs/team/homuntan02.md
  docs/team/nt-nic.md
  docs/team/panpannnnn.md
  docs/team/yyj-02.md
Labels: type.Documentation

#218 217-Add-undo-info-into-UG
  docs/UserGuide.md
  docs/images/undoError.png
Labels: type.Documentation

#222 221-Update DG
  docs/DeveloperGuide.md
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/images/DeleteSequenceDiagram.png
Labels: type.Documentation
